#### importando libreria

In [4]:

import numpy as np



##### listas

In [3]:
lista = list(range(1,11))
print(lista)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


##### lista a array

In [4]:
arreglo = np.array(lista)
arreglo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

#### corroborando el objeto

In [5]:
type(arreglo)

numpy.ndarray

##### corroborando tipo de datos del arreglo

In [6]:
arreglo.dtype

dtype('int32')

##### definiendo el array de int32 a float32

In [7]:
np.array(arreglo, dtype=np.float32)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=float32)

##### sigue siendo un int32

In [8]:
arreglo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

#### transformando el arreglo a float32

In [ ]:
arreglo.np.float32


#### obteniendo la mediana 

In [11]:
mediana = np.median(arreglo)
mediana

5.5

#### desviacion estandar

In [2]:
desviacion_std = np.std(arreglo)
desviacion_std

NameError: name 'np' is not defined

#### nuevo range

In [1]:
arreglonuevo = np.arange(1,11)
arreglonuevo

NameError: name 'np' is not defined

#### arreglo de 2 en 2 utilizando arange

In [ ]:
arreglonuevo2 = np.arange(1,11, 2)
arreglonuevo2

#### funciones de numpy

<h3 style = "color:blue"><b>ALGUNAS FUNCIONES DE NUMPY</b></h4>
<h4 style = "color:aquamarine"><b>COLORES</h3>

#### promedios


In [ ]:
promedio = np.mean(arreglo)
promedio

#### crear un arreglo de puros unos

In [5]:
unos = np.ones(10)
unos
#np.zeros es para crear con ceros

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### convertiendolos a enteros


In [6]:
unos_int = unos.astype(int)
unos_int

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

#### arreglos con randoms

In [7]:
arreglo_randoms = np.random.rand(5)
arreglo_randoms

array([0.69525932, 0.52578617, 0.07231096, 0.86606839, 0.12773536])

#### aleatorios enteros del 1 al 5

In [8]:
aleatorios = np.random.randint(1,5,10)
aleatorios

array([3, 2, 4, 2, 2, 3, 1, 2, 2, 3])

#### matriz aleatoria de 3x3

In [9]:
matriz = np.random.rand(3,3)
matriz


array([[0.43807595, 0.92784941, 0.16799526],
       [0.36137882, 0.39516563, 0.87280248],
       [0.1669996 , 0.5582998 , 0.08320143]])

In [13]:
matriz2 = np.random.randint(1,10,(3,3))
matriz2

array([[1, 2, 5],
       [7, 4, 9],
       [7, 8, 6]])

#### matriz de enteros

In [14]:
matriz3 = np.random.randint(1,100,(10,10))
matriz3

array([[28, 12, 52, 84, 52, 14, 53, 72, 52, 29],
       [66, 47, 38,  4, 48, 81, 77, 34, 74, 65],
       [80, 78, 37, 54, 94, 67, 63, 91,  4, 33],
       [19, 73, 16, 97, 21, 38, 74, 61,  8, 75],
       [64, 28, 48, 45, 55,  5, 36, 86, 34, 94],
       [18, 72, 74, 54, 63, 49,  4, 90, 75, 20],
       [29,  9, 86, 31, 70, 22, 12, 89, 76, 97],
       [36, 97, 40, 63, 68, 30, 32, 83, 51, 76],
       [15, 31, 65, 80, 15,  7, 46,  9, 84,  1],
       [56, 93, 79,  4, 42, 75, 40, 17, 96, 14]])